const tagsColor = (tags) => {
    switch (tags) {
        case "Misc":
            return "bg-slate-300";
        case "Desert":
            return "bg-orange-300";
        case "Meat":
            return "bg-blue-300";
        case "Baking":
            return "bg-pink-400";
        case "Pie":
            return "bg-violet-200";
        case "Cake":
            return "bg-red-400";
        case "Soup":
            return "bg-fuchsia-400";
        case "Breakfast":
            return "bg-yellow-600";
        case "Pudding":
            return "bg-lime-300";
        case "Snack":
            return "bg-amber-400";
        case "Spicy":
            return "bg-slate-400";
        case "Treat":
            return "bg-purple-300";
        case "Curry":
            return "bg-yellow-400";
        case "Pasta":
            return "bg-cyan-200";
        case "Alcoholic":
            return "bg-indigo-300";
        case "Fruity":
            return "bg-green-400";
        case "Speciality":
            return "bg-orange-400";
        case "Sweet":
            return "bg-pink-400";
        case "Vegetarian":
            return "bg-green-400";
        case "Dairy":
            return "bg-yellow-300";
        case "Fish":
            return "bg-blue-300";
        case "Tart":
            return "bg-indigo-400";
        case "BBQ":
            return "bg-red-400";
        case "Chocolate":
            return "bg-brown-300";
        case "MainMeal":
            return "bg-cyan-300";
        case "Seafood":
            return "bg-teal-300";
        case "SideDish":
            return "bg-cyan-300";
        case "Brunch":
            return "bg-yellow-400";
        case "Egg":
            return "bg-yellow-500";
        case "Nutty":
            return "bg-brown-400";
        case "Stew":
            return "bg-red-500";
        case "Calorific":
            return "bg-red-400";
        case "Christmas":
            return "bg-green-400";
        case "DinnerParty":
            return "bg-pink-500";
        case "Pulse":
            return "bg-green-300";
        case "Shellfish":
            return "bg-teal-400";
        case "UnHealthy":
            return "bg-red-400";
        case "Bun":
            return "bg-brown-400";
        case "Casserole":
            return "bg-orange-400";
        case "Cheasy":
            return "bg-yellow-300";
        case "HangoverFood":
            return "bg-indigo-300";
        case "Light":
            return "bg-cyan-300";
        case "Savory":
            return "bg-red-500";
        case "Summer":
            return "bg-yellow-300";
        case "Vegan":
            return "bg-green-400";
        case "Warm":
            return "bg-orange-400";
        case "Warming":
            return "bg-red-300";
        case "Chilli":
            return "bg-red-300";
        case "DateNight":
            return "bg-pink-500";
        case "Glazed":
            return "bg-brown-400";
        case "Halloween":
            return "bg-orange-400";
        case "Heavy":
            return "bg-red-400";
        case "Keto":
            return "bg-purple-300";
        case "LowCarbs":
            return "bg-green-400";
        case "Paleo":
            return "bg-brown-400";
        case "salad":
            return "bg-green-400";
        case "Beans":
            return "bg-green-300";
        case "Caramel":
            return "bg-brown-400";
        case "Easter":
            return "bg-pink-500";
        case "Expensive":
            return "bg-yellow-400";
        case "Fresh":
            return "bg-green-200";
        case "Fusion":
            return "bg-purple-400";
        case "Greasy":
            return "bg-brown-400";
        case "HighFat":
            return "bg-red-500";
        case "LowCalorie":
            return "bg-green-400";
        case "Mild":
            return "bg-green-100";
        case "Onthego":
            return "bg-blue-400";
        case "Paella":
            return "bg-yellow-300";
        case "Sandwich":
            return "bg-brown-300";
        case "Sausages":
            return "bg-red-400";
        case "Sour":
            return "bg-green-500";
        case "Streetfood":
            return "bg-orange-300";
        case "StrongFlavor":
            return "bg-red-400";
        case "Vegetables":
            return "bg-green-300";
        case "pancake":
            return "bg-brown-300";
        case "rice":
            return "bg-yellow-300";
        default:
            return "bg-slate-300";
    }
};

export { tagsColor };
