const tagsColor = (tags) => {
    switch (tags) {
        case "Misc":
            return "bg-slate-500";
        case "Desert":
            return "bg-orange-500";
        case "Meat":
            return "bg-blue-500";
        case "Baking":
            return "bg-pink-600";
        case "Pie":
            return "bg-violet-400";
        case "Cake":
            return "bg-red-700";
        case "Soup":
            return "bg-fuchsia-700";
        case "Breakfast":
            return "bg-yellow-900";
        case "Pudding":
            return "bg-lime-500";
        case "Snack":
            return "bg-amber-700";
        case "Spicy":
            return "bg-slate-700";
        case "Treat":
            return "bg-purple-500";
        case "Curry":
            return "bg-yellow-600";
        case "Pasta":
            return "bg-cyan-300";
        case "Alcoholic":
            return "bg-indigo-500";
        case "Fruity":
            return "bg-green-600";
        case "Speciality":
            return "bg-orange-600";
        case "Sweet":
            return "bg-pink-700";
        case "Vegetarian":
            return "bg-green-700";
        case "Dairy":
            return "bg-yellow-500";
        case "Fish":
            return "bg-blue-600";
        case "Tart":
            return "bg-indigo-700";
        case "BBQ":
            return "bg-red-600";
        case "Chocolate":
            return "bg-brown-500";
        case "MainMeal":
            return "bg-cyan-400";
        case "Seafood":
            return "bg-teal-500";
        case "SideDish":
            return "bg-cyan-500";
        case "Brunch":
            return "bg-yellow-700";
        case "Egg":
            return "bg-yellow-800";
        case "Nutty":
            return "bg-brown-600";
        case "Stew":
            return "bg-red-800";
        case "Calorific":
            return "bg-red-500";
        case "Christmas":
            return "bg-green-700";
        case "DinnerParty":
            return "bg-pink-800";
        case "Pulse":
            return "bg-green-500";
        case "Shellfish":
            return "bg-teal-600";
        case "UnHealthy":
            return "bg-red-600";
        case "Bun":
            return "bg-brown-700";
        case "Casserole":
            return "bg-orange-700";
        case "Cheasy":
            return "bg-yellow-600";
        case "HangoverFood":
            return "bg-indigo-600";
        case "Light":
            return "bg-cyan-600";
        case "Savory":
            return "bg-red-900";
        case "Summer":
            return "bg-yellow-600";
        case "Vegan":
            return "bg-green-800";
        case "Warm":
            return "bg-orange-800";
        case "Warming":
            return "bg-red-600";
        case "Chilli":
            return "bg-red-700";
        case "DateNight":
            return "bg-pink-900";
        case "Glazed":
            return "bg-brown-800";
        case "Halloween":
            return "bg-orange-900";
        case "Heavy":
            return "bg-red-800";
        case "Keto":
            return "bg-purple-600";
        case "LowCarbs":
            return "bg-green-700";
        case "Paleo":
            return "bg-brown-900";
        case "salad":
            return "bg-green-700";
        case "Beans":
            return "bg-green-600";
        case "Caramel":
            return "bg-brown-800";
        case "Easter":
            return "bg-pink-900";
        case "Expensive":
            return "bg-yellow-800";
        case "Fresh":
            return "bg-green-400";
        case "Fusion":
            return "bg-purple-800";
        case "Greasy":
            return "bg-brown-900";
        case "HighFat":
            return "bg-red-900";
        case "LowCalorie":
            return "bg-green-800";
        case "Mild":
            return "bg-green-300";
        case "Onthego":
            return "bg-blue-800";
        case "Paella":
            return "bg-yellow-600";
        case "Sandwich":
            return "bg-brown-500";
        case "Sausages":
            return "bg-red-700";
        case "Sour":
            return "bg-green-900";
        case "Streetfood":
            return "bg-orange-600";
        case "StrongFlavor":
            return "bg-red-800";
        case "Vegetables":
            return "bg-green-500";
        case "pancake":
            return "bg-brown-700";
        case "rice":
            return "bg-yellow-500";
        default:
            return "bg-slate-700";
    }
};

export { tagsColor };
